/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2MiningUserAddPostRequest {
    /// Add new mining account, account name should contain 2-15 lower case letters or numbers, beginning with a letter.
    #[serde(rename = "mining_user_name", skip_serializing_if = "Option::is_none")]
    pub mining_user_name: Option<String>,
}

impl V2MiningUserAddPostRequest {
    pub fn new() -> V2MiningUserAddPostRequest {
        V2MiningUserAddPostRequest {
            mining_user_name: None,
        }
    }
}

