/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2AssetsTransactionsListPostRequest {
    /// Required
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    /// Account name (Only one of mining_user_name and address should be used)
    #[serde(rename = "mining_user_name", skip_serializing_if = "Option::is_none")]
    pub mining_user_name: Option<String>,
    /// Wallet address
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Multiple types are separated by ',' (all, revenue, reward, dividend, flash_exchange, payout)
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Start timestamp
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<i64>,
    /// End timestamp, must be later than start timestamp
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<i64>,
}

impl V2AssetsTransactionsListPostRequest {
    pub fn new() -> V2AssetsTransactionsListPostRequest {
        V2AssetsTransactionsListPostRequest {
            currency: None,
            mining_user_name: None,
            address: None,
            r#type: None,
            start_time: None,
            end_time: None,
        }
    }
}

