/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2MiningUserReadOnlyPageAddPost200Response {
    /// Account name
    #[serde(rename = "mining_user_name", skip_serializing_if = "Option::is_none")]
    pub mining_user_name: Option<String>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<Box<models::ReadOnlyPage>>,
}

impl V2MiningUserReadOnlyPageAddPost200Response {
    pub fn new() -> V2MiningUserReadOnlyPageAddPost200Response {
        V2MiningUserReadOnlyPageAddPost200Response {
            mining_user_name: None,
            page: None,
        }
    }
}

