/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2HashRateDistributionInfoPost200Response {
    #[serde(rename = "current_hash_rate", skip_serializing_if = "Option::is_none")]
    pub current_hash_rate: Option<f64>,
    #[serde(rename = "sold_hash_rate", skip_serializing_if = "Option::is_none")]
    pub sold_hash_rate: Option<f64>,
    #[serde(rename = "remaining_hash_rate", skip_serializing_if = "Option::is_none")]
    pub remaining_hash_rate: Option<f64>,
}

impl V2HashRateDistributionInfoPost200Response {
    pub fn new() -> V2HashRateDistributionInfoPost200Response {
        V2HashRateDistributionInfoPost200Response {
            current_hash_rate: None,
            sold_hash_rate: None,
            remaining_hash_rate: None,
        }
    }
}

