/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2HashRateDistributionTerminatePost200Response {
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl V2HashRateDistributionTerminatePost200Response {
    pub fn new() -> V2HashRateDistributionTerminatePost200Response {
        V2HashRateDistributionTerminatePost200Response {
            reason: None,
        }
    }
}

