/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2MiningUserPaymentPausePostRequest {
    /// Currency type
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    /// Account list
    #[serde(rename = "mining_user_names", skip_serializing_if = "Option::is_none")]
    pub mining_user_names: Option<Vec<String>>,
}

impl V2MiningUserPaymentPausePostRequest {
    pub fn new() -> V2MiningUserPaymentPausePostRequest {
        V2MiningUserPaymentPausePostRequest {
            currency: None,
            mining_user_names: None,
        }
    }
}

