/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2HashRateWorkerListPost200Response {
    #[serde(rename = "workers", skip_serializing_if = "Option::is_none")]
    pub workers: Option<Vec<models::WorkerMiningInfo>>,
}

impl V2HashRateWorkerListPost200Response {
    pub fn new() -> V2HashRateWorkerListPost200Response {
        V2HashRateWorkerListPost200Response {
            workers: None,
        }
    }
}

