/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2MiningUserWalletUpdatePostRequest {
    /// Wallet parameters
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Vec<models::WalletParams>>,
}

impl V2MiningUserWalletUpdatePostRequest {
    pub fn new() -> V2MiningUserWalletUpdatePostRequest {
        V2MiningUserWalletUpdatePostRequest {
            params: None,
        }
    }
}

