/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2MiningUserGetPost200Response {
    /// Account name
    #[serde(rename = "mining_user_name", skip_serializing_if = "Option::is_none")]
    pub mining_user_name: Option<String>,
    /// Read-only page data
    #[serde(rename = "pages", skip_serializing_if = "Option::is_none")]
    pub pages: Option<Vec<models::ReadOnlyPage>>,
    /// Wallet address information of all currencies
    #[serde(rename = "wallets", skip_serializing_if = "Option::is_none")]
    pub wallets: Option<Vec<models::Wallet>>,
    /// Description of the account.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl V2MiningUserGetPost200Response {
    pub fn new() -> V2MiningUserGetPost200Response {
        V2MiningUserGetPost200Response {
            mining_user_name: None,
            pages: None,
            wallets: None,
            description: None,
        }
    }
}

