/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2MiningUserReadOnlyPageAddPostRequest {
    /// Account name
    #[serde(rename = "mining_user_name", skip_serializing_if = "Option::is_none")]
    pub mining_user_name: Option<String>,
    /// Description of the read-only page
    #[serde(rename = "page_name", skip_serializing_if = "Option::is_none")]
    pub page_name: Option<String>,
    /// Permission settings, the same as ReadOnlyPage
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<String>,
}

impl V2MiningUserReadOnlyPageAddPostRequest {
    pub fn new() -> V2MiningUserReadOnlyPageAddPostRequest {
        V2MiningUserReadOnlyPageAddPostRequest {
            mining_user_name: None,
            page_name: None,
            permissions: None,
        }
    }
}

