/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2HashRateDistributionSettlementsPost200Response {
    #[serde(rename = "settlements", skip_serializing_if = "Option::is_none")]
    pub settlements: Option<Vec<models::HashRateDistributionSettlement>>,
}

impl V2HashRateDistributionSettlementsPost200Response {
    pub fn new() -> V2HashRateDistributionSettlementsPost200Response {
        V2HashRateDistributionSettlementsPost200Response {
            settlements: None,
        }
    }
}

