/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2AssetsBalancePost200Response {
    #[serde(rename = "balance_info", skip_serializing_if = "Option::is_none")]
    pub balance_info: Option<Box<models::BalanceInfo>>,
}

impl V2AssetsBalancePost200Response {
    pub fn new() -> V2AssetsBalancePost200Response {
        V2AssetsBalancePost200Response {
            balance_info: None,
        }
    }
}

