/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2MiningUserThresholdUpdatePost200Response {
    /// Payout threshold
    #[serde(rename = "threshold", skip_serializing_if = "Option::is_none")]
    pub threshold: Option<String>,
}

impl V2MiningUserThresholdUpdatePost200Response {
    pub fn new() -> V2MiningUserThresholdUpdatePost200Response {
        V2MiningUserThresholdUpdatePost200Response {
            threshold: None,
        }
    }
}

