/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2MiningUserGetPostDefaultResponse {
    /// Error code
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    /// Error type and description
    #[serde(rename = "msg", skip_serializing_if = "Option::is_none")]
    pub msg: Option<String>,
}

impl V2MiningUserGetPostDefaultResponse {
    pub fn new() -> V2MiningUserGetPostDefaultResponse {
        V2MiningUserGetPostDefaultResponse {
            code: None,
            msg: None,
        }
    }
}

