/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2HashRateInfoListPost200Response {
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<Vec<models::HashRateInfo>>,
}

impl V2HashRateInfoListPost200Response {
    pub fn new() -> V2HashRateInfoListPost200Response {
        V2HashRateInfoListPost200Response {
            info: None,
        }
    }
}

