/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2HashRateHistoryPost200Response {
    #[serde(rename = "history", skip_serializing_if = "Option::is_none")]
    pub history: Option<Vec<models::MiningHistoryItem>>,
}

impl V2HashRateHistoryPost200Response {
    pub fn new() -> V2HashRateHistoryPost200Response {
        V2HashRateHistoryPost200Response {
            history: None,
        }
    }
}

