/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2AssetsSettleModeSwitchPost200Response {
    /// Settle mode
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    /// Active time
    #[serde(rename = "activated_at", skip_serializing_if = "Option::is_none")]
    pub activated_at: Option<i64>,
}

impl V2AssetsSettleModeSwitchPost200Response {
    pub fn new() -> V2AssetsSettleModeSwitchPost200Response {
        V2AssetsSettleModeSwitchPost200Response {
            mode: None,
            activated_at: None,
        }
    }
}

