/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2MiningUserListPost200Response {
    /// Get the list of all mining accounts
    #[serde(rename = "mining_user_list", skip_serializing_if = "Option::is_none")]
    pub mining_user_list: Option<Vec<models::MiningUserInfo>>,
}

impl V2MiningUserListPost200Response {
    pub fn new() -> V2MiningUserListPost200Response {
        V2MiningUserListPost200Response {
            mining_user_list: None,
        }
    }
}

