/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2HashRateInfoListPostRequest {
    /// Request account name or wallet address list, the maximum amount is 100
    #[serde(rename = "reqs", skip_serializing_if = "Option::is_none")]
    pub reqs: Option<Vec<models::UserMiningReq>>,
}

impl V2HashRateInfoListPostRequest {
    pub fn new() -> V2HashRateInfoListPostRequest {
        V2HashRateInfoListPostRequest {
            reqs: None,
        }
    }
}

