/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2MiningUserBalanceWithdrawPost200Response {
    /// Payment timestamp
    #[serde(rename = "paid_time", skip_serializing_if = "Option::is_none")]
    pub paid_time: Option<i64>,
}

impl V2MiningUserBalanceWithdrawPost200Response {
    pub fn new() -> V2MiningUserBalanceWithdrawPost200Response {
        V2MiningUserBalanceWithdrawPost200Response {
            paid_time: None,
        }
    }
}

