/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HashRateInfo {
    /// Account name or worker name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Current hashrate
    #[serde(rename = "hash_rate", skip_serializing_if = "Option::is_none")]
    pub hash_rate: Option<f64>,
    /// The average hashrate of last 1 hour
    #[serde(rename = "h1_hash_rate", skip_serializing_if = "Option::is_none")]
    pub h1_hash_rate: Option<f64>,
    /// The average hashrate of last 24 hours
    #[serde(rename = "h24_hash_rate", skip_serializing_if = "Option::is_none")]
    pub h24_hash_rate: Option<f64>,
    /// The average rejected hashrate of last 1 hour
    #[serde(rename = "h1_stale_hash_rate", skip_serializing_if = "Option::is_none")]
    pub h1_stale_hash_rate: Option<f64>,
    /// The average rejected hashrate of last 24 hours
    #[serde(rename = "h24_stale_hash_rate", skip_serializing_if = "Option::is_none")]
    pub h24_stale_hash_rate: Option<f64>,
    /// The average delayed hashrate of last 24 hours
    #[serde(rename = "h24_delay_hash_rate", skip_serializing_if = "Option::is_none")]
    pub h24_delay_hash_rate: Option<f64>,
    /// The current local hashrate or reported hashrate
    #[serde(rename = "local_hash_rate", skip_serializing_if = "Option::is_none")]
    pub local_hash_rate: Option<f64>,
    /// The average local hashrate or reported hashrate of last 24 hours
    #[serde(rename = "h24_local_hash_rate", skip_serializing_if = "Option::is_none")]
    pub h24_local_hash_rate: Option<f64>,
}

impl HashRateInfo {
    pub fn new() -> HashRateInfo {
        HashRateInfo {
            name: None,
            hash_rate: None,
            h1_hash_rate: None,
            h24_hash_rate: None,
            h1_stale_hash_rate: None,
            h24_stale_hash_rate: None,
            h24_delay_hash_rate: None,
            local_hash_rate: None,
            h24_local_hash_rate: None,
        }
    }
}

