/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MiningHistoryItem {
    /// Timestamp
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    /// Hashrate
    #[serde(rename = "hash_rate", skip_serializing_if = "Option::is_none")]
    pub hash_rate: Option<f64>,
    /// Hashrate rejected
    #[serde(rename = "stale_hash_rate", skip_serializing_if = "Option::is_none")]
    pub stale_hash_rate: Option<f64>,
    /// Hashrate delayed
    #[serde(rename = "delay_hash_rate", skip_serializing_if = "Option::is_none")]
    pub delay_hash_rate: Option<f64>,
    /// Local hashrate or reported hashrate
    #[serde(rename = "local_hash_rate", skip_serializing_if = "Option::is_none")]
    pub local_hash_rate: Option<f64>,
    /// Mining revenues
    #[serde(rename = "normal_reward", skip_serializing_if = "Option::is_none")]
    pub normal_reward: Option<f64>,
    /// Mining revenues of the delayed hashrate
    #[serde(rename = "delay_reward", skip_serializing_if = "Option::is_none")]
    pub delay_reward: Option<f64>,
    /// Online miners
    #[serde(rename = "online_miners", skip_serializing_if = "Option::is_none")]
    pub online_miners: Option<i32>,
}

impl MiningHistoryItem {
    pub fn new() -> MiningHistoryItem {
        MiningHistoryItem {
            timestamp: None,
            hash_rate: None,
            stale_hash_rate: None,
            delay_hash_rate: None,
            local_hash_rate: None,
            normal_reward: None,
            delay_reward: None,
            online_miners: None,
        }
    }
}

