/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadOnlyPage {
    /// /mining-user-{currency}/{key} is the URI of the read-only page
    #[serde(rename = "key")]
    pub key: String,
    /// Different permissions should be separated by comma. 1 means it has permission to view the mining hashrate and worker list. 2 means it has permission to view the revenue data, including the payment information. 3 means it has permission to view the revenue data without payment information
    #[serde(rename = "permissions")]
    pub permissions: String,
    /// Description of the read-only page
    #[serde(rename = "page_name")]
    pub page_name: String,
}

impl ReadOnlyPage {
    pub fn new(key: String, permissions: String, page_name: String) -> ReadOnlyPage {
        ReadOnlyPage {
            key,
            permissions,
            page_name,
        }
    }
}

