/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletParams {
    /// Account name
    #[serde(rename = "mining_user_name", skip_serializing_if = "Option::is_none")]
    pub mining_user_name: Option<String>,
    /// Wallet address configuration list
    #[serde(rename = "wallets", skip_serializing_if = "Option::is_none")]
    pub wallets: Option<Vec<models::Wallet>>,
}

impl WalletParams {
    pub fn new() -> WalletParams {
        WalletParams {
            mining_user_name: None,
            wallets: None,
        }
    }
}

