/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Wallet {
    /// Currency type
    #[serde(rename = "currency")]
    pub currency: String,
    /// Wallet address
    #[serde(rename = "address")]
    pub address: String,
    /// Payout threshold
    #[serde(rename = "threshold")]
    pub threshold: String,
}

impl Wallet {
    pub fn new(currency: String, address: String, threshold: String) -> Wallet {
        Wallet {
            currency,
            address,
            threshold,
        }
    }
}

