/*
 * F2 Pool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// WorkerStatus : Worker status
/// Worker status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WorkerStatus {
    Online = 0,
    Offline = 1,
    Expired = 2,
}

impl ToString for WorkerStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Online => String::from("0"),
            Self::Offline => String::from("1"),
            Self::Expired => String::from("2"),
        }
    }
}

impl Default for WorkerStatus {
    fn default() -> WorkerStatus {
        Self::Online
    }
}

